controller_manager:
  ros__parameters:

    use_sim_time: true
    
    update_rate: 100 #Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    diff_cont:
      type: diff_drive_controller/DiffDriveController
    
    velocity_cont:
      type: velocity_controllers/JointGroupVelocityController

diff_cont:
  ros__parameters:

    publish_rate: 30.0 # You can set this higher than the controller manager update rate, but it will be throttled
    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.4
    wheel_radius: 0.075

    use_stamped_vel: false

velocity_cont:
  ros__parameters:

    joints:
      - left_wheel_joint
      - right_wheel_joint

    command_interfaces:
      - velocity
    
    state_interfaces:
      - velocity
      - effort