<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:macro name="pmzbbot_core" params="">

        <xacro:include filename="inertial_macros.xacro" />

        <xacro:include filename="pmzbbot_common.xacro" />
        <xacro:pmzbbot_common/>

        <xacro:include filename="pmzbbot_ros2control.xacro" />
        <xacro:pmzbbot_control/>

        <!-- BASE LINK -->

        <link name="base_link">
        </link>


        <!-- For Velocity Controller -->
        <joint name="base_footprint_joint" type="fixed">
            <parent link="base_link"/>
            <child link="base_footprint"/>
            <origin xyz="0 0 -${wheel_radius}" rpy="0 0 0"/>
        </joint>

        <!-- BASE_FOOTPRINT LINK -->
        <link name="base_footprint">
        </link>

        <!-- <origin xyz="0 0 ${-wheel_radius + wheel_offset_z}" rpy="0 0 0"/> -->

        <!-- CHASSIS Information -->
        
        <!--joint-->
        <joint name="chassis_joint" type="fixed">
            <parent link="base_link"/>
            <child link="chassis_link"/>
            <origin xyz="${-chassis_offset_x} 0 0"/>
        </joint>
        
        <!--link-->
        <link name="chassis_link">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${(chassis_height/2 - chassis_offset_z)}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${(chassis_height/2 - chassis_offset_z)}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${(chassis_height/2)}" rpy="0 0 0"/>
        </xacro:inertial_box>
        </link>
        
        <!-- LEFT WHEEL -->

        <joint name="left_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="left_wheel"/>
            <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
            <axis xyz="0 0 1"/>
        </joint>

        <link name="left_wheel">
        <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
                <material name="blue"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}"/>
                </geometry>
            </collision>
            <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link>

        <gazebo reference="left_wheel">
            <material>Gazebo/Black</material>
        </gazebo>

        <!-- RIGHT WHEEL -->

        <joint name="right_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="right_wheel"/>
            <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
            <axis xyz="0 0 -1"/>
        </joint>

        <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
        </link>

        <gazebo reference="right_wheel">
            <material>Gazebo/Black</material>
        </gazebo>

        <!-- CASTER WHEEL FONT RIGHT -->

        <joint name="caster_wheel_joint" type="fixed">
            <parent link="base_link"/>
            <child link="caster_wheel"/>
            <origin xyz="${casterwheel_offset_x} 0 -${casterwheel_offset_z}"/>
        </joint>

        <link name="caster_wheel">
            <visual>
                <geometry>
                    <sphere radius="${casterwheel_radius}"/>
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${casterwheel_radius}"/>
                </geometry>
            </collision>
            <xacro:inertial_sphere mass="${casterwheel_mass}" radius="${casterwheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_sphere>
        </link>

        <gazebo reference="caster_wheel">
            <material>Gazebo/Blue</material>
            <mu1 value="0.001"/>
            <mu2 value="0.001"/>
        </gazebo>

        <!-- Ground truth pose -->
        <gazebo>
            <plugin name="groud_truth_pose" filename="libgazebo_ros_p3d.so">
                <always_on>true</always_on>
                <update_rate>50.0</update_rate>
                <body_name>base_footprint</body_name>
                <topic_name>odom</topic_name>
                <gaussian_noise>0.00</gaussian_noise>
                <frame_name>world</frame_name>
                <tf_frame_name>world</tf_frame_name>
                <tf_prefix>odom_groud_truth_pose</tf_prefix>
                <xyz_offset>0 0 0</xyz_offset>
                <rpy_offset>0 0 0</rpy_offset>
                <ros>
                    <remapping>/odom:=odom_groud_truth_pose</remapping>
                </ros>
            </plugin>
        </gazebo>

    </xacro:macro>

</robot>