<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:macro name="pmzbbot_core" params="">

        <xacro:include filename="inertial_macros.xacro" />

        <xacro:include filename="pmzbbot_common.xacro" />
        <xacro:pmzbbot_common/>

        <!-- BASE LINK -->

        <link name="base_link">
        </link>


        <!-- For Velocity Controller -->
        <joint name="base_footprint_joint" type="fixed">
            <parent link="base_link"/>
            <child link="base_footprint"/>
            <origin xyz="0 0 -${wheel_radius}" rpy="0 0 0"/>
        </joint>

        <!-- BASE_FOOTPRINT LINK -->
        <link name="base_footprint">
        </link>

        <!-- <origin xyz="0 0 ${-wheel_radius + wheel_offset_z}" rpy="0 0 0"/> -->

        <!-- CHASSIS Information -->
        
        <!--joint-->
        <joint name="chassis_joint" type="fixed">
            <parent link="base_link"/>
            <child link="chassis_link"/>
            <origin xyz="${-chassis_offset_x} 0 0"/>
        </joint>
        
        <!--link-->
        <link name="chassis_link">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${(chassis_height/2 - chassis_offset_z)}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${(chassis_height/2 - chassis_offset_z)}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${(chassis_height/2)}" rpy="0 0 0"/>
        </xacro:inertial_box>
        </link>
        
        <!-- LEFT WHEEL -->

        <joint name="left_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="left_wheel"/>
            <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
            <axis xyz="0 0 1"/>
        </joint>

        <link name="left_wheel">
        <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
                <material name="blue"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}"/>
                </geometry>
            </collision>
            <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link>
        
        <!-- RIGHT WHEEL -->

        <joint name="right_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="right_wheel"/>
            <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
            <axis xyz="0 0 -1"/>
        </joint>

        <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
        </link>

        <!-- CASTER WHEEL FONT RIGHT -->

        <joint name="caster_wheel_joint" type="fixed">
            <parent link="base_link"/>
            <child link="caster_wheel"/>
            <origin xyz="${casterwheel_offset_x} 0 -${casterwheel_offset_z}"/>
        </joint>

        <link name="caster_wheel">
            <visual>
                <geometry>
                    <sphere radius="${casterwheel_radius}"/>
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${casterwheel_radius}"/>
                </geometry>
            </collision>
            <xacro:inertial_sphere mass="${casterwheel_mass}" radius="${casterwheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_sphere>
        </link>

    </xacro:macro>

</robot>