<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:macro name="pmzbbot_core" params="">

        <xacro:include filename="inertial_macros.xacro" />

        <xacro:include filename="pmzbbot_common.xacro" />
        <xacro:zhbbot_common/>

        <xacro:include filename="pmzbbot_ros2control.xacro" />
        <xacro:zhbbot_control/>


        <!-- BASE_FOOTPRINT LINK -->

        <link name="base_footprint">
        </link>

        <!-- For Velocity Controller -->
        <joint name="base_footprint_joint" type="fixed">
            <parent link="base_link"/>
            <child link="base_footprint"/>
            <origin xyz="0 0 -${wheel_radius}" rpy="0 0 0"/>
        </joint>

        <!-- For Differantial Drive Controller -->
        <!-- <joint name="base_footprint_joint" type="fixed">
            <parent link="base_link"/>
            <child link="base_footprint"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </joint> -->

        <!-- <origin xyz="0 0 ${-wheel_radius + wheel_offset_z}" rpy="0 0 0"/> -->


        <!-- BASE LINK -->

        <link name="base_link">
        </link>


        <!-- CHASSIS Information -->
        
        <!--joint-->
        <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
        </joint>
        
        <!--link-->
        <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </visual>
        <collision>
            <!-- <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/> -->
            <origin xyz="${chassis_length/2} 0 -0.10"/>
            <!-- <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry> -->
            <geometry>
                <mesh filename="file://$(find zhbbot_description)/meshes/mir_100_base.stl"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="100" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
        </link>
        
        <!-- LEFT WHEEL -->

        <joint name="left_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="left_wheel"/>
            <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
            <axis xyz="0 0 1"/>
        </joint>

        <link name="left_wheel">
        <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
                <material name="blue"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}"/>
                </geometry>
            </collision>
            <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link>

        <gazebo reference="left_wheel">
            <material>Gazebo/Black</material>
        </gazebo>

        <!-- RIGHT WHEEL -->

        <joint name="right_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="right_wheel"/>
            <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
            <axis xyz="0 0 -1"/>
        </joint>

        <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
        </link>

        <gazebo reference="right_wheel">
            <material>Gazebo/Black</material>
        </gazebo>

        <!-- CASTER WHEEL FONT RIGHT -->

        <joint name="caster_wheel_f_r_joint" type="fixed">
            <parent link="base_link"/>
            <child link="caster_wheel_f_r"/>
            <origin xyz="${caster_wheel_offset_x} ${caster_wheel_offset_y} ${caster_wheel_offset_z}"/>
        </joint>

        <link name="caster_wheel_f_r">
            <visual>
                <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
                </geometry>
            </collision>
            <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_sphere>
        </link>

        <gazebo reference="caster_wheel_f_r">
            <material>Gazebo/Blue</material>
            <mu1 value="0.001"/>
            <mu2 value="0.001"/>
        </gazebo>

        <!-- CASTER WHEEL FONT LEFT -->
        <joint name="caster_wheel_f_l_joint" type="fixed">
            <parent link="base_link"/>
            <child link="caster_wheel_f_l"/>
            <origin xyz="${caster_wheel_offset_x} ${-caster_wheel_offset_y} ${caster_wheel_offset_z}"/>
        </joint>

        <link name="caster_wheel_f_l">
            <visual>
                <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
                </geometry>
            </collision>
            <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_sphere>
        </link>
        
        <gazebo reference="caster_wheel_f_l">
            <material>Gazebo/Blue</material>
            <mu1 value="0.001"/>
            <mu2 value="0.001"/>
        </gazebo>

        <!-- CASTER WHEEL BACK RIGHT -->
        <joint name="caster_wheel_r_r_joint" type="fixed">
            <parent link="base_link"/>
            <child link="caster_wheel_r_r"/>
            <origin xyz="${-caster_wheel_offset_x} ${caster_wheel_offset_y} ${caster_wheel_offset_z}"/>
        </joint>

        <link name="caster_wheel_r_r">
            <visual>
                <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
                </geometry>
            </collision>
            <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_sphere>
        </link>

        <gazebo reference="caster_wheel_r_r">
            <material>Gazebo/Blue</material>
            <mu1 value="0.001"/>
            <mu2 value="0.001"/>
        </gazebo>

        <!-- CASTER WHEEL BACK LEFT -->
        <joint name="caster_wheel_r_l_joint" type="fixed">
            <parent link="base_link"/>
            <child link="caster_wheel_r_l"/>
            <origin xyz="${-caster_wheel_offset_x} ${-caster_wheel_offset_y} ${caster_wheel_offset_z}"/>
        </joint>

        <link name="caster_wheel_r_l">
            <visual>
                <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
                </geometry>
            </collision>
            <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_sphere>
        </link>

        <gazebo reference="caster_wheel_r_l">
            <material>Gazebo/Black</material>
            <mu1 value="0.001"/>
            <mu2 value="0.001"/>
        </gazebo>

        <!-- Laser  -->
        <joint name="laser_joint" type="fixed">
            <parent link="base_link"/>
            <child link="lidar_link"/>
            <origin xyz="0.122 0 0.312" rpy="0 0 0"/>
        </joint>

        <link name="lidar_link">
            <visual>
                <geometry>
                    <cylinder radius="0.05" length="0.04"/>
                </geometry>
                <material name="red"/>
            </visual>
            <visual>
                <origin xyz="0 0 -0.05"/>
                <geometry>
                    <cylinder radius="0.01" length="0.1"/>
                </geometry>
                <material name="red"/>
            </visual>
        </link>

        <gazebo reference="lidar_link">
                <material>Gazebo/Red</material>
        </gazebo>

        <gazebo reference="lidar_link">
            <sensor name="laser" type="ray">
                <pose> 0 0 0 0 0 0 </pose>
                <visualize>true</visualize>
                <update_rate>5</update_rate>
                <ray>
                    <scan>
                        <horizontal>
                            <samples>360</samples>
                            <min_angle>-3.14</min_angle>
                            <max_angle>3.14</max_angle>
                        </horizontal>
                    </scan>
                    <range>
                        <min>0.25</min>
                        <max>20</max>
                    </range>
                </ray>
                <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                    <ros>
                        <argument>~/out:=scan</argument>
                    </ros>
                    <output_type>sensor_msgs/LaserScan</output_type>
                    <frame_name>lidar_link</frame_name>
                </plugin>
            </sensor>
        </gazebo>

        <!-- Ground truth pose -->
        <gazebo>
            <plugin name="groud_truth_pose" filename="libgazebo_ros_p3d.so">
                <always_on>true</always_on>
                <update_rate>50.0</update_rate>
                <body_name>base_footprint</body_name>
                <topic_name>odom</topic_name>
                <gaussian_noise>0.00</gaussian_noise>
                <frame_name>world</frame_name>
                <tf_frame_name>world</tf_frame_name>
                <tf_prefix>odom_groud_truth_pose</tf_prefix>
                <xyz_offset>0 0 0</xyz_offset>
                <rpy_offset>0 0 0</rpy_offset>
                <ros>
                    <remapping>/odom:=odom_groud_truth_pose</remapping>
                </ros>
            </plugin>
        </gazebo>

    </xacro:macro>

</robot>